83 fix game flow
koodikilpparit/sanapolku pull request #101
Opened 2024-10-23 12:18 UTC by Salonj

Tässä pr on korjattu pelilogiikka vastaamaan asiakkaiden toiveita, jonka lisäksi jaettu pelin phaset omiin komponentteihin jatkokehityksen helpotukseksi.

2024-10-24 17:49 UTC, juhor00 commented
Mikä on se haluttu flow tässä pelissä jos sana menee väärin? En tähän hätään löytänyt muuta kuin Sprint 2 review muistiosta:

> Jos toinen vaihe menee vasta oikein, niin ei siirrytä suoraan seuraavaan sanaan vaan tulee muut vaiheet vielä harjoitukseksi 

Eli ihan oikein se, että jos phase1 menee väärin niin aina tulee phase2 ja phase3. Mutta nyt sen jälkeen se sama sana tulee phase1 uudelleen? Onko se haluttua?

2024-10-24 17:54 UTC, juhor00 requested changes
Hyvä tuo jako eri phaseihin, vaikuttaa hyvin simppeliltä lähteä jatkokehittään niitä itsenäisesti. Lähinnä tuo game flow mietityttää nyt, en ole täysin varma miten sen kuitenkaan pitäisi olla.

2024-10-24 17:54 UTC, juhor00 commented on src/components/game/GameEngine.js
> +        setCurrentPhase(3);
Eikös tämä koko if-else ole täysin turha, jos aina tuloksesta riippumatta siirrytään phase 3 ja tyhjennetään input? Siirrä tuo yhteinen toiminnallisuus pois if-else rakenteesta. Ehdon voi pitää, laita vaikka tyhjät lohkot kommentteineen, niin jatkokehitys siihen päälle on vielä helppoa kuitenkin.

2024-10-26 18:06 UTC, Salonj commented on src/components/game/GameEngine.js
> +        setCurrentPhase(3);
Ei ollu jostain syystä ottanut gittiin mukaan tota päivitettyä pelilogiikkaa vaikka olin sen tehnyt :D

2024-10-27 12:03 UTC, juhor00 approved these changes

2024-10-27 13:59 UTC, merged