53 possibility to remove custom path
koodikilpparit/sanapolku pull request #108
Opened 2024-10-25 10:38 UTC by KiviluomaNeera

Toteutettu mahdollisuus poistaa omia polkuja. Ennen polun poistoa käyttäjältä varmistetaan toimenpide pop up ikkunan avulla. Tässä on myös yhtenäistetty sanan poistamisen nappi hyödyntämään samaa globaalia komponenttia.

Db testit on valmiina. Muut testit toteutan kunhan PR #107 saadaan valmiiksi, sillä siellä voisi olla apuja näidenkin testaamiseen (tai sit en vaan osaaaa :( ). Laitoin nyt kuitenkin jo PR pystyyn niin testejä lukuunottamatta toiminnallisuuden ja koodin voi katselmoida.

Lisäksi korjattu 
- kirjoitusvirhe URL-polussa (muokaa -> muokkaa)
- muutettu pop up ikkunan Tallenna-napin väriä tummemmaksi, jotta se olisi luettavampi
- Korjattu uuden polun lisäämisen yhteydessä teksti "Lisää Uusi Polku" -> "Lisää uusi polku"

2024-10-25 15:45 UTC, juhor00 requested changes
UI näyttää hyvältä ja yhtenäiseltä tuon edit ominaisuuden kanssa. Toimi itsellä ihan oikein.

2024-10-25 15:45 UTC, juhor00 commented on src/db/db.js
> +export function deletePath(pathId) {
Tämän pystyy refaktoroimaan ainakin 2-3 funktioon. Ainakin itse polun poistaminen omasta kannastaan ja sen polun sanojen poistaminen toisesta kannasta on selkeät kokonaisuudet.

Tässä on liikaa sisäkkäisyyksiä, vaikea pysyä perässä mikä kuuluu mihinkäkin lohkoon. Mieluiten yksi tuollainen .onsuccess, .onerror, .oncomplete jne kokonaisuus per funktio.

2024-10-25 15:45 UTC, juhor00 commented on src/pages/PathSelection.js
> +    //navigate(`/muokkaapolkua/${path}`);
Tässä vaiheessa voidaan poistaa koko tämä kommentti. Edit on jo mergettynä myös.

2024-10-25 15:45 UTC, juhor00 commented on src/db/db.test.js
Ei ole välttämätöntä tehdä testiä, mutta eikös poistot tehdä transaktiossa? Olisi mielenkiintoista testata tilanne, jossa polun poisto on OK, mutta sanojen poistamisessa tulee virhe jostain syystä. Onko silloin polku vielä tallella, sillä transaktion pitäisi peruuntua?

2024-10-26 14:05 UTC, KiviluomaNeera commented on src/db/db.test.js
Tää oli hyvä nosto sillä toi tilanne ei toimi ja polku poistuu, vaikka sanat ei poistuisi. Oon hakannut päätä seinään tämän kanssa, koska polun poiston jälkeen onnistuneesti sitä transaktionia ei saa enää estettyä myöhemmin tai ainakaan itse en löytänyt keinoa sille. Onnistuin luomaan tälle todennäköisesti toimivan testin, mutta jätin sen vielä pois muutoksista (löytyy kuitenkin itseltä lokaalisti)

2024-10-27 12:33 UTC, juhor00 requested changes
Koodi on nyt paljon luettavampaa. Vielä laitoin pari kommenttia noista uusista muutoksista. Tuohon uuteen issueen liittyen ei siis tarvitse tässä tehdä mitään, laitetaan vaan sisään vaikka on erillisissä transaktioissa.

2024-10-27 12:33 UTC, juhor00 commented on src/db/db.js
>        const pathTransaction = db.transaction('paths', 'readwrite');
Lueskelin hieman miten tämän IndexedDB:n transactioiden best practiceista. Ensinnäkin me halutaan luoda yksi transaktio joka koskee polun JA sen sanojen poistoa yhtenä kokonaisuutena. `db.transaction` parametriksi voidaan antaa lista object storeja (esim 'paths' ja 'words'). Sitten jonkun operaation epäonnistuessa koko transaktio voidaan perua, eikä tietokanta jää epäkonsistenttiin tilaan.

Katsoin samalla muita tietokanta koodeja ja erityisesti niiden transaktioita. Sama ongelma toistuu muuallakin, ainakin `resetDB()`:ssä. Ei kuulu tämä issuen skooppiin samalla korjata ja testata noita kaikkia, teen oman issuen https://github.com/koodikilpparit/sanapolku/issues/113

2024-10-27 12:33 UTC, juhor00 commented on src/db/db.js
> +  */
Miksi tämä on mukana ja kommentoituna? Mihin tällaista funktiota edes käytettäisiin?

2024-10-27 12:33 UTC, juhor00 commented on src/db/db.js
> +export async function deletePathsWords(pathId) {
Onko mitään syytä miksi tämä exportattaisiin myös? Eikös tuota export voi miettiä ikään kuin private ja public rajapintana? Eikö tätä käytetä vain ja ainoastaan `deletePath` sisällä (joka tietyisti itsessään kuuluu exportata)?

2024-10-27 18:13 UTC, KiviluomaNeera commented on src/db/db.js
> +  */
Hups :D

2024-10-27 18:13 UTC, KiviluomaNeera commented on src/db/db.js
> +export async function deletePathsWords(pathId) {
Hups, jäi testien toteutuksen yhteydestä vahingossa ku homma meni epätoivoseks :D

2024-10-27 18:33 UTC, juhor00 approved these changes

2024-10-27 18:41 UTC, merged