Now own path button is whole container because of changing paddings
koodikilpparit/sanapolku pull request #137
Opened 2024-10-30 17:12 UTC by tuulijar

Muutettu omien polkujen nimien (eli peliin vievien nappien) paddingeja, jotta koko container eli käyttäjälle napilta näyttävä painike vie peliin. Closes #120

2024-10-31 17:32 UTC, juhor00 requested changes
Onko mahdollista että tuolla ympäröivällä path-item-container on tuo onClick ominaisuus, eikä tuolla path-item itsellään? Yhä on tuo pari pikseliä "tyhjää" mistä ei klikkausta oteta mutta highlight tulee. Eli containeria painaessa mennään peliin, paitsi jos sen sijaan ollaan sen sisällä jommassakummassa buttonissa niin silloin klikataan sitä eikä peliin.

2024-10-31 17:49 UTC, tuulijar commented
No voin koittaa kattoo, mut alunperin kun yritin niin, nii jostain syystä sit tavallaan peitti noi muokkaus- ja poistamisnapit "alleen" eikä ne enää toiminut. Vai onkohan sit olemas jotai millä ne saa ns. korkeempaan arvoon ku ton containerin. Täytyy selvittää.

2024-10-31 20:03 UTC, tuulijar commented
Nyt taisin saadakin korjattua tolleen, kun toivoit. Jos siitä poistamis- ja muokkausnapin välistä klikkaa nii jostain syystä se avaa poistamismahdollisuuden. En keksinyt syytä, mutta jos häiritsee niin täytyy ehkä heittää Neeralle nopee issue siitä, kun toteuttanut ton poistamisnapin, niin ehkä helpompi keksiä myös selitys. Korjasin samalla vähän tota sivun ulkonäköä järkevämmäksi, niin vähän useempi muutos koodissa. 

Mites toi ku tuli noit konfliktei ja korjasin ne ja nyt toi niiden mergeeminen heittää coverage testiä jostain syystä miinukselle, niin täytyyks mun sille tehä jotain?

2024-11-01 19:16 UTC, juhor00 approved these changes
Tuo Poista-nappi voisi tosiaan olla paremmin CSS osalta. Se ei kuitenkaan kuulu tämän PR skooppiin enää, tämä toimii hyvin. Teknisesti ei kyllä tämä klikkausaluekaan, mutta se häiritsi itseäni enemmän :D 

Ei tarvitse välittää tuosta coverallsista, ei tässä juuri muuta kuin tyyliseikkoja muokattukaan. Mergeä vaan vaikka se näyttää punaista.

![image](https://github.com/user-attachments/assets/124569cd-b0e3-4b9b-8256-11767c6b4622)

2024-11-01 19:37 UTC, merged