67 fetching photos from papunet
koodikilpparit/sanapolku pull request #140
Opened 2024-10-31 18:00 UTC by Majis-R

This pull request introduces a new modal component and integrates it into the `NewWord` page, along with a photo-fetching feature using the Papunet API. The most important changes include adding the Papunet photo-fetching functionality, and updating the `NewWord` page to use these new features.

### Modal Component and Styles

The modal overlay is supposed to be a temporary way to see the results returned by the API call

* [`src/components/Modal.js`](diffhunk://#diff-c80a14057369079bbb58db6e6af9b9b1a67a4126ea2d5b2cea658c5cc5b80326R1-R19): Added a new `Modal` component to display content in an overlay.
* [`src/components/Modal.css`](diffhunk://#diff-3f13f6ba37c1f4987594132ed0ff307981cfcc43d8d82d9edc5c7d223be3c9f6R1-R32): Defined styles for the modal overlay, content, and close button.

### Papunet Photo Fetching

* [`src/util/PapunetPhotoFetcher.js`](diffhunk://#diff-abf65826a21cc4c17dcba08da1a0883bfee1faebd875a3103777ecd2d794a81eR1-R45): Created a utility class to fetch photos from the Papunet API.
* [`src/util/PapunetPhotoFetcher.test.js`](diffhunk://#diff-be29e3e8155a1bf6b064292f736b6020f9e18629dfebe1bed43fce4ee543ddffR1-R56): Added tests for the `PapunetPhotoFetcher` class to ensure it handles API responses and errors correctly.
* [`src/pages/PapunetView.js`](diffhunk://#diff-246f79c9a4d43aba46665b3f1eafa62cb782b6ff9cae32c40af919a9e4965fa2R1-R68): Implemented the `PapunetView` component to fetch and display photos, with the ability to select an image.
* [`src/pages/PapunetView.css`](diffhunk://#diff-2c731b8b7f7885b89dbbc3b3139b1b3e5e05d40dc7203a86a81c9ea7e4ee7728R1-R59): Added styles for the `PapunetView` component, including the photo fetcher and photo container.

### Integration with `NewWord` Page

The implementation currently allows for sellecting an image from Papunet and saving it to the database and using the image in game. The selected image preview is currently displayed as the placeholder image but saving it works nevertheless and it works well in game

* [`src/pages/NewWord.js`](diffhunk://#diff-de0073097b87017eae1bb76c303f4ddd787bf281b369d0c38a5072b7315a2962R7-R8): Integrated the `Modal` and `PapunetView` components into the `NewWord` page, allowing users to fetch and select photos. [[1]](diffhunk://#diff-de0073097b87017eae1bb76c303f4ddd787bf281b369d0c38a5072b7315a2962R7-R8) [[2]](diffhunk://#diff-de0073097b87017eae1bb76c303f4ddd787bf281b369d0c38a5072b7315a2962R17) [[3]](diffhunk://#diff-de0073097b87017eae1bb76c303f4ddd787bf281b369d0c38a5072b7315a2962R87-R105)

### Debug Configuration

* [`.vscode/launch.json`](diffhunk://#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945R1-R17): Added a new debug configuration for the React app using Chrome.

2024-11-01 19:56 UTC, juhor00 requested changes
Kuvien haku toimii oikein näppärästi! En kiinnittänyt tässä reviewissä tyyliseikkoihin huomiota, tärkeätä vain saada toiminnallisuus testattavaksi oikeaan ympäristöön ASAP. Olit kuitenkin tehnyt siitä tarpeeksi hyvän että on miellyttävä testata. Toisin kuin minä Share-juttujen kanssa :D Testi caset ovat myös järkeviä ja helppoja ymmärtää.

Muutamia yksityiskohtia laitoin kommentteihin jotka olisi hyvä korjata / huomioida.

2024-11-01 19:56 UTC, juhor00 commented on .vscode/launch.json
Tämä ei ainakaan itselläni toimi? Kun käynnistän VSCodesta tällä launch configuraatiolla niin avaa selaimeen localhost:3000 ja printtailee Debug Consoleen (VSCodessa) muutaman warning / error rivin. Ei koskaan saa mitään yhteyttä. Miten tämän on tarkoitus toimia, ja vaatiiko se lisää säätämistä?

Joko konffaa tästä plug-and-play tai jätetään kokonaan pois. Kuitenkin npm start taitaa tehdä pitkälti saman asian?

2024-11-01 19:56 UTC, juhor00 commented on src/components/Modal.js
Osaatko perustella miksi isOpen olisi prop joka annetaan tälle komponentille ja se itse päättää renderöidäänkö se vai ei? Itse näkisin parempana että siinä komponentissa jossa tämä Modal halutaan avata tehdään joku `{isOpen && <Modal/>}`

2024-11-01 19:56 UTC, juhor00 commented on src/pages/PapunetView.js
> +    }
`fetchPhotos()` ei koskaan heitä erroria, sillä siellä catchataan kaikki errorit ja palautetaan tyhjä lista. Nyt konsoliin tulee virheviesti, mutta käyttäjä ei tiedä että virhe tapahtui. Tykkään enemmän ajatuksesta, että tehdään kuten tässä ja asetetaan setError joka näkyy käyttäjälle, mutta ei rikota näkymää (tyhjä lista hakutuloksia). Poista siis tuon funktion sisältä virheenkäsittely.

2024-11-01 19:56 UTC, juhor00 commented on src/utils/PapunetPhotoFetcher.js
> +class PapunetPhotoFetcher {
Onko mitään erityistä syytä luoda luokka jolla on staattisia funktioita pelkästään? Tuo parsePhotos vaikuttaa muutenkin vain apufunktiolta, ainoastaan fetchPhotos taitaa olla käytössä ulkopuolelta? Eikö sen voisi exporttaa yksinään?

2024-11-01 19:56 UTC, juhor00 commented on src/utils/PapunetPhotoFetcher.test.js
> +);
Tätä ei käytetä mihinkään? Ainoa testihän testaa toimintaa kun API ei toimi. Tämä voisi kaivata jotain testejä success-scenaarioille myös. Esimerkiksi tyhjä hakutulos ja useampi kuva hakutuloksessa.

2024-11-03 15:13 UTC, Majis-R commented on .vscode/launch.json
Tämä oli sen vuoksi että saan liitettyä vscoden debuggerin. Jos tiedät paremman tavan niin tahtoisin tietää. Toimii minun laitteellani kunhan vain on ajanut ensin komennon `npm start` ja ei muuta oletusporttia. En ole ihan varma että miten se pitäisi confata muille koneille kun en tarkalleen tiedä miksi ei toimi. VSCodessa pitää varmaankin asettaa oikea debuggeri kun sitä kysytään. Kuitenkin voi varmaan laittaa tuon tiedoston gitignoreen.

2024-11-03 15:22 UTC, Majis-R commented on src/components/Modal.js
Ajattelin sen sillai modulariteetin kannalta. Muistaakseni ajattelin tehdessä että noin ehkä vähän helpompi uudellenkäyttää johonkin muuhunkin ja se renderöidään aina samalla tavalla. Mutta joo tuntuu että pääasiassa mieltymyskysymys ja tuo modaali oli muutenkin nopea ratkaisu kun halusin jonkun paikan johon laittaa haetut tulokset

2024-11-03 16:10 UTC, Majis-R commented on src/utils/PapunetPhotoFetcher.js
> +class PapunetPhotoFetcher {
Tämä tulee puhtaasti siitä että en tiedä miten javascript toimii. Varmaan fiksumpaa juuri noin. Tässä taustalla joku javasta opittu juttu että kaiken täytyisi olla aina jonkin luokan sisällä. Korjattu [05e71c61ac73b92bac0bb6a847c7f64938e3af1d](https://github.com/koodikilpparit/sanapolku/pull/140/commits/05e71c61ac73b92bac0bb6a847c7f64938e3af1d)

2024-11-03 17:21 UTC, Majis-R commented on src/utils/PapunetPhotoFetcher.test.js
> +);
Joo tuo on vähän hölmö testi. Kirjoitin uudet järkevämmät. Korjattu [f5554e5eb734f0708b51e1db899cb3d961c3cb23](https://github.com/koodikilpparit/sanapolku/pull/140/commits/f5554e5eb734f0708b51e1db899cb3d961c3cb23)

2024-11-03 17:51 UTC, Majis-R commented on src/components/Modal.js
Olisiko ollut myös ajatusta että modaali voisi pysyä auki eri näkymien välillä navigoitaessa. Ei varmaan oikeasti tarpeellinen ja voi varmaan tehdä muullakin tavalla. En näe että tässä kohtaa ihan liikaa väliä voi siirtää vaikka siihen issueen missä UI on oikeasti tarkoitus toteuttaa

2024-11-03 18:02 UTC, juhor00 commented on .vscode/launch.json
Tuo olikin "Attach"-tyylinen debuggeri, ajattelin että se myös itsessään launchaa siis. Kyllä tuo toimii mullakin ihan oikein siis nyt kun kokeilin. Sitten ok, pidetään vaan mukana. Tuo on ihan hyödyllinen.

2024-11-03 18:08 UTC, juhor00 commented on src/components/Modal.js
Joo, on tuokin siis ihan ok. Tuntui vaan itsestä oudolta, mutta vähän kun tutkin niin nimenomaan tuollaisten modal komponenttien kanssa ihan validi lähestymistapa tuokin. Ei tarvitse tehdä mitään muutoksia tuolle.

2024-11-05 15:44 UTC, juhor00 approved these changes
Nyt vaikuttaa hyvältä ja toimivalta. Virheetkin käsitellään. Tämän pohjalta on hyvä lähteä jatkamaan UI kehitystä!

Laitoin yhden kommentin tuohon `useRef` käyttöön liittyen. Sen voi jaksaessaan vaihtaa `useState`, mutta approvaan myös tällaisenaankin.

2024-11-05 15:44 UTC, juhor00 commented on src/pages/PapunetView.js
> +  const initialFetchDone = useRef(false);
Miksi tässä käytetään referenssiä staten sijaan? Ainoa mihin "referoidaan" on true/false. Ainakin se oma tietämys Reactista on se että tässä ennemmin olisi järkevää käyttää useState.

2024-11-05 19:47 UTC, merged