22 implement phase one for word in game
koodikilpparit/sanapolku pull request #142
Opened 2024-11-01 15:42 UTC by annikniem

Issuessa #22 toteutettiin pelin 1-vaiheen UI UI-suunnitelman mukaisesti. Input-kenttä on nyt vaihdettu kirjainlaatoiksi, joille voi kirjoittaa näppäimistöllä. UI:hin renderöityy niin monta kirjainlaattaa kuin kyseisessä sanassa on kirjaimia ja pelaajan kirjoittaessa näppäimistöllä kirjainlaatat täyttyvät järjestyksessä yksitellen. Pelaaja voi myös poistaa kirjoittamiaan kirjaimia 'Backspace'-näppäimellä. Pelaaja voi siirtyä pelin seuraavaan vaiheeseen joko painamalla näppäimistön 'Enter'-nappia tai klikkaamalla 'valmis'-nappia. Pelin logiikka itsessään toimii samalla tavalla kuin aiemminkin. 

Tässä yhteydessä siistittiin myös GamePage-sivun ulkonäköä. Pelisivulle lisättiin takaisin-nappi ja sivun otisikoiden, tekstien sekä pelin sisällön (eli eri vaiheisiin kuuluvien komponenttien) asettelua ja ulkonäköä paranneltiin. Pelin logiikkaa päivitettiin toimimaan uudesta vaiheen 1 input-tyylistä huolimatta.

Vaiheelle 1-toteutettiin myös UI:n skaalautuvuus niin että komponentit asettuvat näytölle miellyttävän näköisesti riippumatta näytön koosta. Komponenttien pitäisi skaalautua ainakin yleisimmille puhelinten, tablettien ja tietokoneiden näytöille mukavan näköisesti. Lisäksi UI:n pitäisi näyttää hyvältä eri pituisilla sanoilla: kun kirjainlaatat eivät mahdu enää vierekkäin ne jakautuvat useammalle riville. (Pisin sana, jolla testasin on 'Pyyhkäisyelektronimikroskooppi', joka on ilmeisesti yksi suomenkielen pisimpiä sanoja:D). Tämä ei varmaan toimi kuitenkaan loputtomiin, vaan jos polulla on aivan äärettömän pitkiä sanoja, jossain kohtaa ne eivät enää mahdu nätisti näytölle (ehkä voisi olla järkevää asettaa sanoille maksimipituus?).

Lisäksi tämän issuen yhteydessä toteutettiin yksikkötestit pelin 1-vaiheelle. Näissä testataan mm. että UI päivittyy odotetusti pelaajan kirjoittaessa ja että pelaajan tässä vaiheessa antama input tallentuu oikein pelin sisäistä logiikkaa varten. Myös pelin logiikan yksikkötestit päivitettiin toimimaan uudesta input-tyylistä huolimatta ja yksi yksikkötesti lisätiin takaisin-napin toiminnalle.

2024-11-01 18:32 UTC, juhor00 requested changes
Mobiililaitteella ei pysty kirjoittamaan mitään. Laattojen klikkaaminen ei avaa näppäimistöä, eikä muutakaan input-tapaa ole. Koneellakin kaipaisin kursoria tai jotain muuta indikaattoria siihen mikä on aktiivinen laatta. Se myös indikoisi että niihin kirjoitetaan.

UI elementit ovat mielestäni melko alhaalla. Onko ajateltu miten ne sitten toimivat kun se näppäimistö pompahtaa alhaalta? Vai olisiko helpompi jos kaikki olisi valmiiksi vähän ylempänä?

Saisiko tähän jo samalla toiminnon joka ei mahdollista sanan hyväksymistä enterillä tai "Valmis" napilla jos kaikkiin laattoihin ei ole kirjoitettu? Esim. antaisi jonkun hetkellisen punaisen reunan laatoille (ei kuitenkaan pysyvä). En ole varma halutaanko tällaista toimintoa, mutta se omaan silmään vaikuttaisi vähentävän käyttäjän vahinkotoimintoja.

Muutoin tuo phase1 näyttää hyvältä omalla mobiililaitteellani. Elementit ovat sopivan kokoisia, ja eri preseteillä se myös näyttää oikein hyvältä!

Tässä vielä taskeihin jaettuna (myös muut kommentit mitä laitoin PR:ään)

- [x] Korjaa mobiililaitteen input
- [ ] Mieti UI huomioiden se, että näppäimistö nousee mobiililaitteella näkymään
- [x] Lisää kursori tai muu keino ilmaista mihin ollaan kirjoittamassa?
- [x] Älä hyväksy sanaa jos kaikkia kirjaimia ei ole kirjoitettu?
- [ ] Jos mahdollista eikä conflictaa muiden branchien kanssa niin jaa Phase välinen toiminta omaksi komponentikseen?

2024-11-01 18:32 UTC, juhor00 commented on src/components/game/Phase1.css
> +.image-container img {
Jokaisessa vaiheessa varmaan halutaan että kuva pysyy samassa paikassa ja se on aina saman kokoinen? Olisiko siihen liittyvää koodia ja css tyyliä mahdollista käyttää omana komponenttinaan joita vaan viljellään noihin eri vaiheisiin? Jos ne nyt luodaan erikseen joka phasessa ja jokaisella on samat tyylit kopiona, niin tulee paljon duplikaatti tavaraa ja muutos yhdessä paikassa ei vaikuta muualle.

2024-11-04 22:51 UTC, Salonj commented
Meitsi otti koppii tästä et saadaan nopeemmin noi phaset tehtyä! (Sovittiin tää Annin kaa ratikas)

2024-11-06 19:15 UTC, juhor00 requested changes
Skaalautuvuuteen olisi hyvä panostaa jo tässä vaiheessa. Nyt nuo muut näkymän elementit riippuvat hyvin pitkälti siitä minkä kokoinen tuo itse kuva on. Vaikka se tulee olemaan sopivaksi rajattu jo tietokantaan tallentaessa, niin tässä peli vaiheessa ei tule sitä olettaa. Samalla laitteella kaikkien eri kuvien kohdalla näkymän tulee olla identtinen. Eli määritä kuva elementin koko näytön koosta. Skaalaa kuvat pienemmäksi tai isommaksi tarvittaessa. Venytyksistä ei tarvitse nyt välittää, oleta että kuvat tulevat neliönä TAI ne voi venyttää vapaasti.

Jos ehdit, niin koita hieman katsella tuota skaalautuvuutta eri asennoissa eri laitteilla. Esim puhelimella vaakaan (isolla kuvalla) tuo on käyttökelvoton parhaillaan.
![image](https://github.com/user-attachments/assets/0229e270-76ed-438c-9bc1-127755d1df6e)

Tässä pieni checklist vielä:

- [ ] Korjaa kuvan skaalautuvuus
- [ ] Poista turhat kommentit
- [ ] Korjaa Phase2 virhe
- [ ] (Optional) paranna Phase1 skaalautuvuutta

2024-11-06 19:15 UTC, juhor00 commented on src/components/game/GameEngine.js
> +    if (!/^[A-Ö]*$/.test(value)) {
@KiviluomaNeera kanssa tuli puheeksi tätä reviewatessa, että ei oteta inputille rajoitetta. Se lähinnä hämää käyttäjää, kun koko näppäimistö annetaan käyttöön mutta puolet näppäimistä ei visuaalisesti tee mitään. Jos joku haluaa käyttää esim. numeroita sanassa niin antaa palaa.

2024-11-07 19:22 UTC, juhor00 approved these changes
Toiminnallisuus on ok, katsotaan css asioita jatkoissuessa tarkemmin. Mergetään kaikki phaset kerralla 3 --> 2 --> 1 --> main

2024-11-08 07:20 UTC, merged