128 Randomized word order in game
koodikilpparit/sanapolku pull request #173
Opened 2024-11-06 21:09 UTC by tuulijar

Issuessa oli tarkoitus toteuttaa pelin sanojen random järjestys. Toteutin sen sekä muokkasin testit toimimaan tolla random järjestyksellä sekä kattamaan mahdollisimman laajasti eri testikeissejä. Closes #128

2024-11-06 21:22 UTC, tuulijar commented
Näköjään toi coverage vähän kärsi, kun toteutin noi testit vähän eri tavalla, kun mitä ne aiemmin oli. Koitin kuitenkin kattoo, että kaikki oleellinen tulee testattua.

2024-11-12 10:26 UTC, tuulijar commented
Nyt pitäisi testit olla päivitetty toimimaan sovelluksen tän hetkisen tilan kanssa. Aika näkyi punasena, mutta siitä en ollut ihan varma onko se "virhe" vai ei.

2024-11-12 13:53 UTC, juhor00 requested changes
Toimii oikein!
Poista tuo turha elementti joka on vain testejä varten. Se ei sinänsä testaa mitään olennaista, ja on muutenkin best practices vastainen.

2024-11-12 13:53 UTC, juhor00 commented on src/components/game/GameEngine.js
> +            <div data-testid="word-count" style={{ display: 'none' }}>
Tämmöisen lisääminen pelkästään testejä varten ei ole suositeltavaa. Yksikkötesteissäkin halutaan testata toiminnallisuutta, ei itsessään ohjelman sisäistä tilaa. Tätä käytetään vain siihen, että todetaan "words" -tilamuuttujalla olevan tietty arvo.

Sen sijaan oikea lähestymistapa olisi kirjoittaa testi joka etenee sanasta toiseen 10 kertaa, jonka jälkeen peli päättyy. Näyttäisikin siltä, että tälle on jo kirjoitettuna yksikkötesti? Tämän hidden div ja tätä käyttävän yksikkötestin voi minun mielestäni poistaa kokonaan.

2024-11-12 13:53 UTC, juhor00 commented on src/components/game/GameEngine.test.js
>    });
Edelliseen kommenttiin viitaten tämän voi siis poistaa kokonaan.

2024-11-12 13:53 UTC, juhor00 commented on src/components/game/GameEngine.test.js
>    });
Tämä on se yksikkötesti joka testaa että nimenomaan 10 sanaa tulee, eikä enempää. Ei tarvitse siis tähän tehdä muutoksia, kunhan viittasin aikaisempiin kommentteihin liittyen miten tulee toimia.

2024-11-12 13:54 UTC, juhor00 commented on src/components/game/GameEngine.js
> +            </div>
Tämmöisen lisääminen pelkästään testejä varten ei ole suositeltavaa. Yksikkötesteissäkin halutaan testata toiminnallisuutta, ei itsessään ohjelman sisäistä tilaa. Tätä käytetään vain siihen, että todetaan "words" -tilamuuttujalla olevan tietty arvo.

Sen sijaan oikea lähestymistapa olisi kirjoittaa testi joka etenee sanasta toiseen 10 kertaa, jonka jälkeen peli päättyy. Näyttäisikin siltä, että tälle on jo kirjoitettuna yksikkötesti? Tämän hidden div ja tätä käyttävän yksikkötestin voi minun mielestäni poistaa kokonaan.

2024-11-12 14:24 UTC, juhor00 approved these changes

2024-11-12 16:18 UTC, merged