177 fix the word input
koodikilpparit/sanapolku pull request #198
Opened 2024-11-12 15:19 UTC by Salonj

Tässä on päivitetty sanojen input käyttämään hidden inputtia, jotta saadaan toivottavasti eri laitteiden väliset erot korjattua. Samalla on päivitetty komponenttien testejä, jotta ne toimivat uusien päivitysten kanssa.

2024-11-14 19:12 UTC, juhor00 requested changes
Muutama korjattava asia mitä tuli mieleen
- [ ]  Backspace vaatii 2 painallusta pyyhkimään kirjain. Korjaa se yhteen
- [ ] Nyt kaikki kolme phasea kopioivat käytännössä saman toteutuksen tuosta kirjoittamisesta. Toki se tulee muuttumaan phase2:ssa jatko PR:ssä, mutta silti 2/3. Jos ei ole liian vaivalloista, niin siirrä se toteutus yhteiseksi komponentiksi. Muutoin ilmoita niin tehdään jatkoissue QA viikolle esim
- [ ] Kokeilin tabletilla, niin jos jatkaa kirjoittamista viimeisenkin lohkon jälkeen, niin näytölle ei tule lisää tavaraa, mutta se kirjoittuu jonnekin kyllä. Esim jos kirjoitan 100 kirjainta extraa, niin pitää painaa backspacea yhtä monta kertaa ennen kuin alkaa näkyvät ruudut poistua. Tietokoneella tätä ei tapahdu.

2024-11-14 19:34 UTC, juhor00 commented
Lisäyksenä tuohon reviewiin:
Tabletilla pitää AINA näpytellä backspacea paljon. Vaikuttaisi siltä, että aina pitää poistaa yhtä monta kirjainta kun olen YHTEENSÄ kirjoittanut. Vasta sen jälkeen se alkaa vähentämään kirjaimia ruudulta. Tuo "tyhjän poistaminen" tapahtuu siis vaikken olisi koko sanaa vielä kirjoittanutkaan. Se ei tapahdu jos vaihdan kursorin johonkin tiettyyn kohtaan. Se ei myöskään tapahdu jos näpäytän kursorin esimerkiksi loppuun ja alan sitten tyhjentämään. Kursoria vaihtaessa tuleekin joku inputin "reload", näppis menee hetkeksi pois ja tulee takaisin. Sille ei ole välttämätöntä tehdä mitään, mutta tuo backspace toiminta pitää kyllä korjata.

2024-11-15 20:55 UTC, Salonj commented on src/components/game/Phase1.js
> +    if (event.key === 'Backspace') {
Fiksasin loogisemmaksi.

2024-11-15 20:58 UTC, Salonj commented
Jaoin input-komponentin omaksi moduulikseen, jota käytetään nyt Phase 1:ssä ja 3:ssa. Päivitin myös backspace-logiikkaa toimimaan sulavammin. Yritin korjata bugin, jossa tableteilla pystyi kirjoittamaan sallitun merkkimäärän yli. Testatessa puhelimella ongelmaa ei enää ilmennyt, mutta en ole varma, onko se täysin korjattu tableteilla.

2024-11-17 13:39 UTC, juhor00 commented
Backspace taitaa toimia nyt oikein. Tabletilla tulee yhä samat ongelmat. Johtunee tuosta onKeyDown inputista, se ei taida olla kaikilla mobiililaitteilla yhtä toimintavarma tapa kuin tietokoneella. Voin itse kokeilla tehdä jonkun korjauksen.

2024-11-18 18:07 UTC, closed without merging