164 add music
koodikilpparit/sanapolku pull request #227
Opened 2024-11-20 15:36 UTC by Salonj

### 🎉🎉Taustabiisi lisätty

<img src="https://media4.giphy.com/media/Sg86rhq4G3vqM/giphy-downsized-medium.gif"/>

Toteutettu taustabiisi asiakkaan toivomille sivuille eli kaikkialle muualle kuin pelivaiheeseen. Selaimen asettamien rajoitteiden takia biisi lähtee soimaan vasta kun käyttäjä on ollut vuorovaikutuksessa sivun kanssa. Pelivaiheessa musiikki menee mykistykselle, jotta saadaan vältettyä tämä selaimen rajoite pelistä poistuessa.

2024-11-20 20:38 UTC, Salonj commented on src/components/sounds/BackgroundMusic.js
> +  const { music, volume = 0.5 } = useContext(SettingsContext);
Joo mä laskin tätä 0.25, ehkä nyt ois parempi :D

2024-11-20 20:44 UTC, Salonj commented
Lisäsin nyt vielä ton faden noihin ääniin, niin ei lopu ihan seinään toi musa :D

2024-11-20 20:53 UTC, juhor00 commented
Ainakin peliin mennessä toi fade out on aika pitkäkestonen. Joku kymmenisen sekuntia taitaa mennä peräti. Fade in on ihan ok, parisen sekuntia. Fixaa vielä toi fade out (ainakin peliin mennessä menee silleen)

2024-11-24 22:33 UTC, juhor00 requested changes
Tehtiin oma fix PR muutamista asioista. Huomattiin, että tabletilla tulee tällaista virhettä:

![image](https://github.com/user-attachments/assets/1de2aec3-f240-4565-87f7-57d7cef95660)

Rivinumero saattaa olla eri kuin tässä branchissa, mutta suuntaa antava. Tuleeko sulla mobiililaitteella samaa? Sain myös toistumaan tuon virheen jos menee suoraan osoitteeseen http://localhost:3000/data/audio/hittibiisi.mp3

2024-11-25 17:45 UTC, juhor00 approved these changes

2024-11-25 18:30 UTC, merged