28 enhance the UI
koodikilpparit/sanapolku pull request #290
Opened 2024-12-04 16:40 UTC by tuulijar

Fixattu:

- Kännykällä vaakatasossa kuusitausta näkyviin, jos ei ole polkuja: Ei onnistunut eritellä, joten nyt aina näkyvissä ja saattaa jäädä elementtien taakse piiloon, jolloin ei näy

- Hitusen pidemmällä polun nimellä kännykällä editointi, poisto ja jakonapit liukuvat ulos ruudusta, jolloin niitä ei voi enää käyttää (Kuva kommenteissa). Mallia voi varmaankin ottaa pitkän sanan käsittelystä polun muokkauksen sivulta: Jakautuu nyt uudelle riville, kuten sanalistoissakin

- Polun jakamisen vastaanottamisen ponnahdusikkunassa Palaa Takaisin nappia voisi pienentää (ei näy ainakaan Juhon tabletilla kokonaan :D): Pienennetty, onko tarpeeksi?

Closes #28

2024-12-04 18:29 UTC, juhor00 requested changes
Polun valinta sivu on oikein hyvä, järkyttävän pitkä polku (satoja merkkejä :D) näytti yllättävän hyvältä. 👍
Laitoin muutamilta komponenteilta ton background colorin pois, niin nyt toi tausta näyttää hyvältä, eikä oo nii tyhjän näkönen enää 👌
Palaa takaisin -nappi polun vastaanottamissivulla on nyt hyvä. Näkyy kokonaan mun tabletilla :D 

Kato saisiks ton yhen toisen kommentoidun jutun hoidettua viel nii sit all good
![BoratBoratVeryNiceGIF](https://github.com/user-attachments/assets/50686341-8292-4bf1-9fca-ab101a0f64ab)

2024-12-04 18:29 UTC, juhor00 commented on src/styles/PathSelection.css
Polun nimi peittää napit polun muokkaus -näkymässä (editointi, uuden sanan lisäys). Keksisitkö sille jonkun fixin, että ainakin se lisää nappi olisi aina näkyvissä? Plussaa jos edit nappi myös.

2024-12-05 10:24 UTC, KiviluomaNeera approved these changes
Juho pyysi et tsekkaan tän loppuun. Tää näyttää oikein hyvältä ja hyvä et sai molemmat napit pidettyä näkyvillä! 

![GoodFineGIF](https://github.com/user-attachments/assets/ed4ca990-b6a8-4d7e-94c0-d16e7b40b8a7)

2024-12-05 10:32 UTC, tuulijar commented
Mä en jostain syystä pysty mergee, en tiiä johtuuko siitä et Juho on merkannut et pitää muuttaa eikä oo hyväksynyt niitä muutoksii, mut jos @KiviluomaNeera tai sit @juhor00 sen verran et heittää mainiin vaik nii thänks!

2024-12-05 10:35 UTC, juhor00 approved these changes

2024-12-05 10:36 UTC, merged

2024-12-05 10:36 UTC, juhor00 commented
Saat kunnian (toivottavasti) viimeisen PR:n mergetä ite

2024-12-05 10:36 UTC, KiviluomaNeera commented
Sori ehin jo ::D

2024-12-05 10:36 UTC, juhor00 commented
Oh no :D

2024-12-05 10:37 UTC, KiviluomaNeera commented
![OopsAquamanGIF](https://github.com/user-attachments/assets/611a884d-441d-43d5-98c6-0867f4b4498b)

2024-12-05 10:38 UTC, juhor00 commented
![BummerButOkayAndySambergGIF](https://github.com/user-attachments/assets/f3bedcd2-339f-4f75-ad57-a4db1a1a4f03)