10 implement main view
koodikilpparit/sanapolku pull request #40
Opened 2024-10-03 10:02 UTC by annikniem

Closes #10 

Tällä tiketillä totetutettiin sovelluksen start-sivu. Kaikki sivun komponentit löytyvät src/components/start polun kautta. Komponentit on lisätty start-sivulle ja start-sivulle on toteutettu UI-suunnitelman mukaiset tyylit. Package.json ja packag-lock.json tiedostoihin on lisätty tarvittavat riippuvuudet FontAwesome-ikonien käyttöä varten.

Start-sivulla on yksi turha header, joka sisältää "Sanapolku"-tekstin ja on asetettu näkymättömäksi. Tämä on vain siksi, että koodi läpäisee kaikki testit (yksi testi tarkistaa, että sivulla on "Sanapolku" teksti ja muuten testi ja pipeline epäonnistuvat). Onko tämä tarkoituksenmukaista? Pitäisikö ensin muuttaa tätä testiä, poistaa sitten UI:sta turha teksti ja sitten suorittaa merge mainiin vai mennäänkö tällä?:)

2024-10-03 10:44 UTC, pampula commented
Mun puolesta turhan tekstin voi poistaa ja testiä vaikka muokata toisenlaiseksi! Se oli lähinnä väliaikainen ratkaisu, kun joku testi piti olla, ettei herjaile mitään. :)

2024-10-03 14:52 UTC, juhor00 requested changes
Etusivu näyttää mainiolta ja koodit ovat siistit ja selkeät!
Onnistuisiko jo tämän PR yhteydessä tehdä yksikkötestejä etusivun toiminnasta? Lähinnä että vaaditut elementit renderöityvät tällä sivulla, ja nappia painamalla siirtyy oikelle sivulle. Vaikka tuntuisivat nyt turhilta, niin myöhemmin ne auttavat takaamaan että tällaiset perustoiminnot toimivat oikein, eikä uudet muutokset riko näitä.

2024-10-03 14:52 UTC, juhor00 commented on src/pages/Start.js
> +            <h2 className="invisible-text"> Sanapolku</h2>
Kuten Eve sanoikin jo, niin otetaan tämä pois kokonaan. Testin voi muokata sellaiseksi, että se varmistaa että sivulle renderöidään tietyt elementit. Jos koet, ettei se testi ole merkityksellinen missään määrin, niin sitten mieluummin vain poistetaan kokonaan.

2024-10-03 14:53 UTC, juhor00 commented
Korjaa myös `package-lock.json` conflictit

2024-10-05 13:31 UTC, annikniem commented on src/pages/Start.js
> +            <h2 className="invisible-text"> Sanapolku</h2>
Nyt pitäisi olla kaikki ok!
- Se App-komponentin testi on muutettu niin, että se testaa ainoastaan, että App-komponentti renderöityy.
- Start-sivulta on poistettu turha "Sanapolku"-teksti ja siihen liittyvä turha koodi on poistettu myös Start.css -tiedostosta
- Merge konfliktit pitäisi olla nyt ratkaistu package-lock.json tiedoston osalta
- Lisäksi Start-sivulle on toteteutettu yksikkötestit, joissa testataan, että sivu komponentteineen renderöityy ja että navigointi toimii niinkuin pitäisikin

2024-10-06 10:01 UTC, juhor00 approved these changes
Package-lock.json tiedostossa näyttää yhä olevan conflicteja, korjaa ne ennen mergeä. Täytyy jatkossa hieman tutkia ylipäätään tuon pitämistä gitissä ja onko tähän parempia työkaluja. Manuaalisesti tuollaisen ylläpitäminen on melko turhaa ja työlästä.

2024-10-06 14:38 UTC, annikniem commented
@juhor00 
 Nyt pitäisi vihdoin oikeesti olla kaikki merge konfliktit ratkaistua! Siihen voisi kyllä tosiaan miettiä jonkun paremman keinon ylläpitää. On aika työlästä manuaalisesti ylläpitää sitä. 

Korjasin lisäksi UI:sta pienen virheen. Keskialueen komponentit menivät osittain Asetukset-napin päälle, jolloin sitä ei voinut klikata kuin asetukset-ikonin yläosasta. Nyt nappi on kokonaan klikattavissa.

2024-10-06 14:48 UTC, merged