5 implement view for infopage
koodikilpparit/sanapolku pull request #58
Opened 2024-10-13 15:55 UTC by Majis-R

2024-10-13 17:24 UTC, juhor00 requested changes
Sivu toimii hyvin ja asetukset tallentuvat oikein, ja ne asetetaan sinne minne kuuluukin.
Mitään kirjautumiseen tai käyttäjätietoihin liittyvää ei ole tulossa, joten tuo nimi, id ja "Kirjaudu ulos" ovat kaikki turhia. Ne kannattaa vaan poistaa tässä vaiheessa, ei jää turhaan pyörimään.

Samalla kun ne poistaa, niin asetukset voisi laittaa tuohon keskelle ruutua, ja "Tieto sovelluksesta" olisi sen alla.

Taustaväri ei skaalaudu oikein mobiilinäkymässä kun alkaa viemään ikkunaa hyvin kapeaksi. Vastaava korjaus on tehty jo tässä, kannattaa katsoa esimerkkiä jos saat helpolla saman korjaksen tähän: https://github.com/koodikilpparit/sanapolku/pull/49/commits/ecd03d7b3ab3bbdae355ccaf19398bc0cc732978

Lopuksi vielä hyvin olematon asia: yksikkötesteissä voitaisiin yhtenäisesti käyttää `it()` tuon `test()` sijaan (taitavat olla sama asia)

Tässä vielä checklista:

- [ ] Poista kirjautumiseen liittyvät elementit
- [ ] Keskitä loput sivun elementit
- [ ] Korjaa taustan skaalautuvuus
- [ ] Vaihda `test()` --> `it()`

2024-10-14 12:02 UTC, Majis-R commented
- [ ] Palauta oletustilaan nappi

2024-10-19 12:31 UTC, Majis-R commented
Tehty kaikki ehdotetut muutokset. 

Lisätty myös funtio tietokannan tyhjentämiseen

2024-10-19 13:06 UTC, juhor00 requested changes
Muuten laittaisin jo Approven tässä vaiheessa, mutta hoidetaan tuo ihan pieni asia pois jonka kommentoin index.js tiedostoon. Tuo toinen kommentti kuva tietokannan poistamisesta on ihan up to you teetkö vielä tämän PR yhteydessä vai teetkö siitä vain uuden issuen ja hoidetaan se sen yhteydessä.

Olennaisinta on, että saadaan tämä PR hoidettua pois alta maanantaiksi, niin voidaan esitellä asiakkaalle toteutettuja muutoksia.

2024-10-19 13:06 UTC, juhor00 commented on src/db/db.js
> +export function resetDB() {
Eikö kuvatkin pitäisi poistaa ImageDatabasesta? Nyt ne jäävät tietokantaan eikä mikään edes referoi niihin enää.

2024-10-19 13:24 UTC, Majis-R commented on src/db/db.js
> +export function resetDB() {
Teen tästä erillisen issuen

2024-10-19 13:28 UTC, Majis-R commented on src/index.js
> +  document.getElementById('root')
Minulle ei jostain syystä tule tästä varoitusta. Poistin kuitenkin kyseisen rivin

2024-10-19 13:34 UTC, juhor00 approved these changes

2024-10-19 13:37 UTC, merged