19 implement game logic
koodikilpparit/sanapolku pull request #81
Opened 2024-10-20 19:50 UTC by Salonj

Toteutettu pelilogiikka “pelimoottorin” kautta, joka tarjoaa oikean näkymän pelin vaiheesta riippuen. Peli etenee kolmessa vaiheessa: sanan kirjoittaminen, kirjainten järjestäminen, ja sanan kopiointi. Peliä voi testata korvaamalla PathSelection.js-tiedostossa seuraavan koodin:

```
const handlePathClick = (path) => {
navigate(`/peli/${path}`);
// navigate(`/muokaapolkua/${path}`);
  };
```

2024-10-21 07:07 UTC, Salonj commented
Lisätäänn vielä:

- Peliivaiheiden siirtymä kuntoon
- Sanojen kaikki kirjaimet isoksi/pieneksi

2024-10-21 09:18 UTC, juhor00 requested changes
Pelin logiikka toimii hyvin. Rakenne on järkevä.

Mikä on tuon Reactin staten scope? Taitaa tyhjentyä aina reloadissa? Olisiko kannattavaa tutkia miten esim. session storagen scope vertautuu? Saisiko tilan tallennettua yhdelle sessiolle siten, ettei pelkkä reload vielä nollaa pelin kulkua? (Se olisi jatkoissuen asiaa).

Tein tähän muutaman muokkauspyynnön koskien toteutusyksityiskohtiin ja virheidenkäsittelyyn lähinnä.

2024-10-21 09:18 UTC, juhor00 commented on src/components/game/GameEngine.js
> +  const shuffleWord = (word) => {
Nopeasti tutkittuani tämä ei taida olla hirveän hyvä random shuffle. Suosittelen etsimään ja käyttämään jotain hyväksi todettua kirjastoa.

2024-10-21 09:18 UTC, juhor00 commented on src/pages/GamePage.test.js
> +  it('checks if Instructions-page renders', () => {
Onko jäänyt copy pastessa toisen testin tekstit? En näe miten olisi tähän relevanttia puhua Instructions-pagesta

2024-10-21 09:18 UTC, juhor00 commented on src/pages/PathSelection.js
> +    //navigate(`/peli/${path}`);
Ennemmin jätetään commitoimatta kommentoitua koodia. On aina riski että tämä muutos tulee muuta kautta eri tavalla ja epähuomiossa kommentti jää. Jatkoissuen kohdalla jossa se nappi muutenkin tulee voidaan hoitaa tämä samalla.

2024-10-21 09:18 UTC, juhor00 commented on src/components/game/GameEngine.css
Oletan että tähän on tulossa myöhemmin pelisivun tyylit? En oikein silti tykkää, että tässä vaiheessa commitoidaan ja referoidaan tyhjään fileen joka ei tee vielä mitään. Ei tarvitse kuitenkaan poistaa turhaan

2024-10-21 10:20 UTC, Salonj commented on src/pages/GamePage.test.js
> +  it('checks if Instructions-page renders', () => {
Joo jäi 😭

2024-10-21 19:25 UTC, Salonj commented on src/components/game/GameEngine.js
> +  const shuffleWord = (word) => {
Käytin tässä nyt parempaa algoritmia (Durstenfeld shuffle)

https://en.wikipedia.org/wiki/Fisher–Yates_shuffle

2024-10-22 19:44 UTC, juhor00 approved these changes

2024-10-22 19:44 UTC, merged